#!/usr/bin/env bash

TMP_PACKAGE_OLD="$1"
TMP_PACKAGE_NEW="$2"

if  [ "$TMP_PACKAGE_OLD" = "$TMP_PACKAGE_NEW" ] ||
    [ "$TMP_PACKAGE_OLD" = "" ] ||
    [ "$TMP_PACKAGE_NEW" = "" ] ||
    [ ! -d "$TMP_PACKAGE_OLD" ] ||
    [ ! -d "$TMP_PACKAGE_NEW" ]; then
  echo './migrate old-package new-package'
  exit 1
fi

echo ""
echo -e "\033[7m \033[3mMigrating\033[0m\033[7m \033[1m$TMP_PACKAGE_OLD \033[0m"
cd "$TMP_PACKAGE_OLD"
git clone ssh://aur@aur.archlinux.org/${TMP_PACKAGE_OLD}.git
cp "../$TMP_PACKAGE_NEW/PKGBUILD" $TMP_PACKAGE_OLD/
cp "../$TMP_PACKAGE_NEW/.SRCINFO" $TMP_PACKAGE_OLD/
cd $TMP_PACKAGE_OLD
git add -f PKGBUILD .SRCINFO
git commit -m "Migrated ${TMP_PACKAGE_OLD} -> ${TMP_PACKAGE_NEW}"
git push
cd ..
rm -rf $pkgname
cd ..
echo ""

unset TMP_PACKAGE_OLD
unset TMP_PACKAGE_NEW
