#!/usr/bin/env bash

pkgname="$1"
pkgver="$2"

arch=(aarch64 armv7l x86_64)

checkFiles() {
  local a;
  local file;
  for a in "${arch[@]}"; do
    file="${pkgname}-${a}-${pkgver}.tar.gz"
    if [ ! -f "$file" ]; then
      echo 0
      return
    fi
  done
  echo 1
}

removeFiles() {
  local a;
  local b;
  local valid;
  for a in $(ls ${pkgname}-*.tar.gz); do
    valid=0
    for b in $(ls ${pkgname}-*-${pkgver}.tar.gz); do
      if [ "$a" = "$b" ]; then
        valid=1
      fi
    done
    if [ "$valid" = "0" ]; then
      echo "removing $a"
      rm -rf $a
    fi
  done
}

getHash() {
    for hash in $("${1}sum" $2); do
        echo $hash
        return
    done
}

getSums() {
  local a;
  local file;
  for a in "${arch[@]}"; do
    file="${pkgname}-${a}-${pkgver}.tar.gz"
    echo "sha256sums_${a}=('$(getHash sha256 ../$file)')"
    if [ "$a" = "armv7l" ]; then
      echo "sha256sums_armv7h=('$(getHash sha256 ../$file)')"
    fi
  done
}

echo ''

if [ "$pkgname" = "" ] || [ "$pkgver" = "" ]; then
  echo -e "\033[1m400\033[0m both package name and version are needed"
  echo ''
  echo '  ./update cog-wpe-bin 0.8.0'
  echo ''
  exit 1
fi

if [ ! -d "$pkgname" ]; then
  echo -e "\033[1m404\033[0m folder ${pkgname} not found"
  echo ''
  exit 1;
fi

if [ "$(checkFiles)" = "0" ]; then
  echo -e "\033[1m404\033[0m ${pkgname} ${pkgver} version not found"
  echo ''
  exit 1
fi

echo -e "\033[7m \033[3mPublishing\033[0m\033[7m \033[1m$pkgname \033[0m \033[1m${pkgver}\033[0m"

git add .
git reset --hard
git pull --rebase

cd "$pkgname"
git clone ssh://aur@aur.archlinux.org/${pkgname}.git
cp TEMPLATE $pkgname/PKGBUILD
getSums >> $pkgname/PKGBUILD
echo '
package () {
    cp -R "${srcdir}/usr" "${pkgdir}"
}
' >> $pkgname/PKGBUILD

cd $pkgname

if [ -f .SRCINFO ]; then
  rm .SRCINFO
fi

makepkg --printsrcinfo > .SRCINFO

git add -f PKGBUILD .SRCINFO
git commit -m "Updated ${pkgname}"
git push origin master

cd ..
rm -rf $pkgname
cd ..

removeFiles

git add .
git commit -m "Published ${pkgname}-${pkgver}"
git push origin master

unset pkgname
unset pkgver
unset arch

echo ''
